print(type(2))
print(type("Hello World!"))
print(type(3.14))
print(type(True))

a = int(1)
b = int(3.14)
c = int("3")
c1 = int(float("3.14"))
d = float(1)
e = float(2.5)
f = float("3")
g = float("4.23")
h = str("80s")
i = str(22)
j = str(3.01)

print([a, b, c, c1, d, e, f, g, h, i, j])
